/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        m3: {
          primary: '#0B664B',
          'on-primary': '#FFFFFF',
          'primary-container': '#D7F1E3',
          'on-primary-container': '#002115',
          secondary: '#6E5C38',
          'on-secondary': '#FFFFFF',
          'secondary-container': '#F8E0BA',
          'on-secondary-container': '#261A02',
          tertiary: '#855320',
          'on-tertiary': '#FFFFFF',
          'tertiary-container': '#FFDCBF',
          'on-tertiary-container': '#2D1600',
          surface: '#FCF9F5',
          'surface-dim': '#DED9D2',
          'surface-bright': '#FCF9F5',
          'surface-container-lowest': '#FFFFFF',
          'surface-container-low': '#F7F3ED',
          'surface-container': '#F1EDE6',
          'surface-container-high': '#EBE7E0',
          'surface-container-highest': '#E5E1DB',
          'on-surface': '#1C1B19',
          'on-surface-variant': '#474742',
          outline: '#787772',
          'outline-variant': '#C8C6C0',
          error: '#BA1A1A',
          'on-error': '#FFFFFF',
          'error-container': '#FFDAD6',
          'on-error-container': '#410002',
        }
      },
      fontFamily: {
        sans: ['var(--font-english-family)', 'Inter', 'Roboto', 'Montserrat', 'system-ui', 'sans-serif'],
        english: ['var(--font-english-family)', 'Inter', 'sans-serif'],
        urdu: ['var(--font-urdu-family)', '"Jameel Noori Nastaleeq"', '"Noto Nastaliq Urdu"', 'serif'],
        arabic: ['var(--font-urdu-family)', '"Traditional Arabic"', '"QuranFont-Original"', '"_PDMS_Saleem_QuranFont"', '"QuranFont"', '"Alyamama"', 'serif'],
        telugu: ['var(--font-telugu-family)', '"Anek Telugu"', '"Noto Sans Telugu Local"', 'sans-serif'],
        jameel: ['"Jameel Noori Nastaleeq"', 'serif'],
        kasheeda: ['"Jameel Noori Kasheeda"', '"Jameel Noori Nastaleeq"', 'serif'],
        sameer: ['"AA Sameer Sagar"', '"Jameel Noori Nastaleeq"', 'serif'],
        alqalam: ['"AlQalam Taj"', '"Jameel Noori Nastaleeq"', 'serif'],
        faiz: ['"Faiz Lahori"', '"Jameel Noori Nastaleeq"', 'serif'],
        quran: ['"Al Qalam Quran Publisher"', '"QuranFont-Original"', '"_PDMS_Saleem_QuranFont"', '"QuranFont"', '"Traditional Arabic"', '"Amiri"', '"Alyamama"', 'serif'],
        alyamama: ['"Alyamama"', '"Traditional Arabic"', 'sans-serif'],
        montserrat: ['"Montserrat"', 'sans-serif'],
        bebas: ['"Bebas Neue Pro"', '"Oswald"', 'sans-serif'],
        oswald: ['"Oswald"', 'sans-serif'],
        roboto: ['"Roboto"', 'sans-serif'],
      },
      boxShadow: {
        'm3-1': '0px 1px 3px 1px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(0, 0, 0, 0.12)',
        'm3-2': '0px 2px 6px 2px rgba(0, 0, 0, 0.08), 0px 1px 2px 0px rgba(0, 0, 0, 0.15)',
        'm3-3': '0px 4px 10px 3px rgba(0, 0, 0, 0.08), 0px 1px 3px 0px rgba(0, 0, 0, 0.15)',
        'm3-4': '0px 6px 14px 4px rgba(0, 0, 0, 0.08), 0px 2px 4px 0px rgba(0, 0, 0, 0.15)',
        'm3-5': '0px 8px 18px 6px rgba(0, 0, 0, 0.08), 0px 3px 6px 0px rgba(0, 0, 0, 0.15)',
      }
    },
  },
  plugins: [],
}
